sonar.projectKey=vetcar
sonar.projectName=vetcar
sonar.sources=app,components,lib,prisma
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/.next/**,**/generated/**,public/**
sonar.test.inclusions=__tests__/**/*.test.ts,__tests__/**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
